export const GET_TOURNAMENTS = 'GET_TOURNAMENTS'
export const GET_TOURNAMENTS_ERROR = 'GET_TOURNAMENTS_ERROR'
export const GET_TOURNAMENTS_LOADING = 'GET_TOURNAMENTS_LOADING'
export const GET_TOURNAMENT = 'GET_SINGLE_TOURNAMENT'
